account/urls.py
from django.conf.urls import url,include
from . import views

urlpatterns = [
	url(r'^login',views.LoginView.as_view(),name='login'),
	url(r'^logout',views.LogoutIndex.as_view(),name='logout'),
	url(r'^profile',views.View_Profile,name='view_profile'),
    url(r'^signup',views.signup, name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^password_reset_index/',views.PasswordResetIndex.as_view(),name='password_reset_view'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_ \ -]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.PasswordConfirmResetIndex.as_view(),name='password_reset_confirm'),
    url(r'^password_reset_complete_view/',views.PasswordCompleteResetIndex.as_view(),name='password_reset_complete_view'),
    url(r'^password_reset_done_view/',views.PasswordResetDoneIndex.as_view(),name='password_reset_done_view'),
    url(r'^upload',views.UploadIndex.as_view(),name='upload'),
]

blog/urls.py
from django.conf.urls import url,include
from .views import (
	CreateView,
	ArtikelDetailView,
	ArtikelManageView,
	ArtikelUpdateView,
	ArtikelDeleteView,
	ArtikelListView,
	ArtikelKategoriListView,
	)

urlpatterns = [
    url(r'^create', CreateView.as_view(),name='create'),
    url(r'^detail/(?P<slug>[\w-]+)$',ArtikelDetailView.as_view(),name='detail'),
	url(r'^manage/$',ArtikelManageView.as_view(),name='manage'),
	url(r'^manage/update/(?P<pk>\d+)$',ArtikelUpdateView.as_view(),name='update'),
	url(r'^manage/delete/(?P<pk>\d+)$',ArtikelDeleteView.as_view(),name='delete'),
	url(r'^(?P<page>\d+)$',ArtikelListView.as_view(),name='list'),
	url(r'^kategori/(?P<kategori>[\w]+)/(?P<page>\d+)$',ArtikelKategoriListView.as_view(),name='category'),

]

my_website/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import index 
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',index.as_view(),name='index'),
    ###
    url(r'^artikel/',include('blog.urls',namespace='blog')),
    url(r'^account/',include('account.urls',namespace='account')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.


class UserProfile(models.Model):
	user = models.OneToOneField(User)
	description = models.CharField(max_length=100,default='',null=True,blank=True)
	city = models.CharField(max_length=100,default='',null=True,blank=True)
	website = models.URLField(default='',null=True,blank=True)
	phone = models.IntegerField(default=62)
	image = models.ImageField(upload_to='profile_image',blank=True,null=True)

	title = models.TextField()
	
	def __str__(self):
		return "{}".format(self.user.username)	

	@property
	def get_photo_url(self):
	    if self.image and hasattr(self.image, 'url'):
	        return self.image.url
	    else:
	        return "/static/img/default.jpg"

            

def create_profile(sender,**kwargs):
	if kwargs['created']:
		user_profile = UserProfile.objects.create(user=kwargs['instance'])


post_save.connect(create_profile,sender=User)

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserProfile

class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')   

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')





class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

class UserEdit(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['city','website','description','phone']

class UploadForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['image']

account/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from django.views.generic.edit import FormMixin
from django.contrib.auth.models import User 
from django.views.generic import TemplateView
from django.views.generic import TemplateView,DetailView,CreateView,ListView
## confirmation email ##
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .forms import SignupForm,UploadForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.core.mail import send_mail
from django.core.mail import EmailMessage
from django.contrib.auth.views import (
    LoginView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    LogoutView,

    )
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.contrib.auth.mixins import LoginRequiredMixin
from .models import UserProfile
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from .forms import UserUpdateForm,UserEdit

class LogoutIndex(LoginRequiredMixin,LogoutView):
	template_name = 'account/logout.html'


class LoginIndex(LoginView):
    template_name = 'account/login.html'

class PasswordResetIndex(PasswordResetView):
    template_name = 'account/password_reset.html'
    success_url = reverse_lazy('account:password_reset_done_view')
    email_template_name = 'account/password_reset_email.html' 

class PasswordResetDoneIndex(PasswordResetDoneView):
    template_name = 'account/password_reset_done.html'

class PasswordConfirmResetIndex(PasswordResetConfirmView):
    template_name = 'account/password_reset_confirm.html'
    success_url = reverse_lazy('account:password_reset_complete_view')

class PasswordCompleteResetIndex(PasswordResetCompleteView):
    template_name = 'account/password_reset_complete.html'

class LoginView(LoginView,FormMixin):
	template_name = 'login.html'


 

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your blog account.'
            message = render_to_string('acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            email.send()
            return HttpResponse('Silakan konfirmasi akun kamu dengan link yang sudah kami kirim ke Mail ')
    else:
        form = SignupForm()

    return render(request, 'signup.html', {'form': form})




def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        # return redirect('home')
        return HttpResponse('Selamat akun kamu sudah aktif dan sudah bisa digunakan ')
    else:
        return HttpResponse('Link tidak valid atau sudah pernah dibuka')

@login_required
def View_Profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = UploadForm(request.POST,
                                   request.FILES,
                                   instance=request.user.userprofile)
        e_form = UserEdit(request.POST,instance=request.user.userprofile)
        if u_form.is_valid() and p_form.is_valid() and e_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Perubahan telah tersimpan')
            return redirect('account:view_profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = UploadForm(instance=request.user.userprofile)
        e_form = UserEdit(instance=request.user.userprofile)

    context = {
        'u_form': u_form,
        'p_form': p_form,
        'e_form': e_form,
        'user':request.user
    }


    return render(request, 'view_profile.html', context)


class UploadIndex(CreateView):
    model = UserProfile
    form_class = UploadForm
    success_url = reverse_lazy('account:view_profile')
    template_name = 'account/upload.html'

account/templates/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Selamat Datang, terima kasih sudah mau mendaftar.Akun anda saat ini belum aktif dan belum bisa digunakana, untuk mengaktifkannya klik link di bawah ini.
http://{{ domain }}{% url 'account:activate' uidb64=uid token=token %}

Salam dari Admin
B.X.Nzo
{% endautoescape %}

account/templates/login.html
<!DOCTYPE html>
<html>
<head>
	<title>Login</title>
</head>
<body>
	<h3>Login Here</h3>
	<p>{{mes}}</p>
	<form method="post">
		{% csrf_token %}
		{{form.as_p}}
		<button type="submit">Login</button>
	</form>
</body>
</html>

account/templates/signup.html
{% extends "base.html" %}

{% block head %}
<title>Signup</title>
{% endblock %}

{% block contents %}

  {% include "snippets/navbar.html" %}
  <form method="post">
      <h2>Sign up</h2>
    {% csrf_token %}
      {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="display: none">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
      {% endfor %}    <button type="submit">Sign up</button>
  </form>
{% endblock %}

account/templates/view_profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head %}
	<title>Profile</title>
{% endblock %}

{% block contents %}
{% include "snippets/navbar.html" %}
<div class="row">
<div class="container">
	<h3>Profile</h3>
	<p>Username:{{user}}</p>
	<p>First name : {{user.first_name}}</p>
	<p>Last name : {{user.last_name}}</p>
	<p>email : {{user.email}}</p>
	<p>Description: {{user.userprofile.description}}</p>
  <p>Kota: {{user.userprofile.city}}</p>
	<p>Phone: {{user.userprofile.phone}}</p>
	<p>Website: {{user.userprofile.website}}</p>
	<img src="{{ user.userprofile.get_photo_url }}" width="240">
	    <div class="content-section">
      <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Ubah Foto</legend>
              {{ u_form|crispy }}
              {{ p_form|crispy }}
              {{e_form|crispy}}


          </fieldset>
          <div class="form-group">
              <button class="btn btn-outline-info" type="submit">Update</button>
          </div>
      </form>

  </div>
  </div>
</div>
{% endblock %}