blog/urls.py
from django.conf.urls import url,include
from .views import (
	CreateView,
	ArtikelDetailView,
	ArtikelManageView,
	ArtikelUpdateView,
	ArtikelDeleteView,
	ArtikelListView,
	ArtikelKategoriListView,
	)

urlpatterns = [
    url(r'^create', CreateView.as_view(),name='create'),
    url(r'^detail/(?P<slug>[\w-]+)$',ArtikelDetailView.as_view(),name='detail'),
	url(r'^manage/$',ArtikelManageView.as_view(),name='manage'),
	url(r'^manage/update/(?P<pk>\d+)$',ArtikelUpdateView.as_view(),name='update'),
	url(r'^manage/delete/(?P<pk>\d+)$',ArtikelDeleteView.as_view(),name='delete'),
	url(r'^(?P<page>\d+)$',ArtikelListView.as_view(),name='list'),
	url(r'^kategori/(?P<kategori>[\w]+)/(?P<page>\d+)$',ArtikelKategoriListView.as_view(),name='category'),

]

my_website/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import index 
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',index.as_view(),name='index'),
    ###
    url(r'^artikel/',include('blog.urls',namespace='blog')),
    url(r'^account/',include('account.urls',namespace='account')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.utils import timezone

class Artikel(models.Model):
	judul 		= models.CharField(max_length=255)
	isi   		= models.TextField()
	kategori 	= models.CharField(max_length=255)
	dibuat 	= models.DateTimeField(auto_now_add=True)
	updated 	= models.DateTimeField(auto_now=True)
	#is_published = models.NullBooleanField(default=False)
	published = models.DateTimeField(null=True)
	slug 		= models.SlugField(blank=True,editable=False)

	def save(self):
		self.slug = slugify(self.judul)
		super().save()

	def get_absolute_url(self):# sehinggan saat selesai create di akan menggunakan dan menggambil absolute dan menampalikan di detail
		url_slug = {'slug':self.slug}
		return reverse('blog:detail',kwargs = url_slug)
		# reverse == mengembalikan
		# get_absolute_url tujuan setelah createview di buat, dan reverse mengembalikan ke detail yang dimana url nya ada slug

	def __str__(self):
		return "{}.{}".format(self.id,self.judul)
"""	class Meta:
		default_permissions = ('add','change','delete')# membuat hanya add saja,lakuan sebelum migrate, alternatifnya jika sudah di migrate lakukan unmakemigrations akan kembali awal
		permissions = (
			('publish_artikel','Can publish artikel'),# untuk custom gunakan permission
			)"""


"""
	def save(self):
		if self.is_published == True:
			self.published = timezone.now()

		else:
			self.published = None 
		super().save()"""

blog/forms.py
from django.forms import ModelForm
from .models import Artikel

class ArtikelForm(ModelForm):
	class Meta:
		model = Artikel
		fields = [
			'judul',
			'isi',
			'kategori'
		]

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView,CreateView,DeleteView,UpdateView,TemplateView
from .models import Artikel
from .forms import ArtikelForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from django.contrib.auth.models import User

	### Penulis ###

class CreateView(UserPassesTestMixin,CreateView):
	template_name = 'blog/create.html'
	form_class = ArtikelForm
	raise_exception = True

	
	def test_func(self):
	    return self.request.user.groups.filter(name='penulis').exists() 
	
	


	#### Editor User ####

class ArtikelManageView(UserPassesTestMixin,ListView):
	model = Artikel 
	template_name = 'blog/artikel_manage.html'
	context_object_name = 'artikel_list'
	raise_exception = True

	def test_func(self):
	    return self.request.user.groups.filter(name='editor').exists() 

class ArtikelDeleteView(UserPassesTestMixin,DeleteView):
	model = Artikel 
	template_name = 'blog/artikel_delete_confirmation.html'
	success_url = reverse_lazy('blog:manage')
	raise_exception = True

	def test_func(self):
	    return self.request.user.groups.filter(name='editor').exists() 

class ArtikelUpdateView(UserPassesTestMixin,UpdateView):
	login_url = None
	form_class = ArtikelForm 
	model = Artikel 
	template_name = 'blog/artikel_update.html'
	raise_exception = True

	def test_func(self):
	    return self.request.user.groups.filter(name='editor').exists() 


	#### View ####

class ArtikelDetailView(DetailView):
	model = Artikel 
	template_name = 'blog/detail.html'
	context_object_name = 'artikel'

	def get_context_data(self,*args,**kwargs):
			kategori_list = self.model.objects.values_list('kategori',flat=True).distinct()
			self.kwargs.update({'kategori_list':kategori_list})
			artikel_serupa = self.model.objects.filter(kategori=self.object.kategori).exclude(id=self.object.id)
			self.kwargs.update({'artikel_serupa':artikel_serupa})
			kwargs = self.kwargs
			return super().get_context_data(*args,**kwargs)

class ArtikelListView(ListView):
	model = Artikel 
	template_name = 'blog/artikel_list.html'
	context_object_name = 'artikel_list'
	ordering = ['-published']
	paginate_by = 3

	def get_context_data(self,*args,**kwargs):
		kategori_list = self.model.objects.values_list('kategori',flat=True).distinct()
		self.kwargs.update({'kategori_list':kategori_list})
		kwargs = self.kwargs
		return super().get_context_data(*args,**kwargs)


class ArtikelPerKategori():
	model = Artikel 

	def get_latest_artikel_each_kategori(self):
		kategori_list = self.model.objects.values_list('kategori',flat=True).distinct()
		queryset = []

		for kategori in kategori_list:
			artikel = self.model.objects.filter(kategori=kategori).latest('published')
			queryset.append(artikel)

		return queryset
class ArtikelKategoriListView(ListView):
	model = Artikel
	template_name = "blog/artikel_kategori_list.html"
	context_object_name = 'artikel_list'
	ordering = ['-published']
	paginate_by = 3

	def get_queryset(self):
		self.queryset = self.model.objects.filter(kategori=self.kwargs['kategori'])
		return super().get_queryset()

	def get_context_data(self,*args,**kwargs):
		kategori_list = self.model.objects.values_list('kategori',flat=True).distinct().exclude(kategori=self.kwargs['kategori'])
		self.kwargs.update({'kategori_list':kategori_list})
		kwargs = self.kwargs
		return super().get_context_data(*args,**kwargs)

blog/templates/blog/artikel_delete_confirmation.html
{% extends "base.html" %}

{% block head %}
<title>Delete</title>
{% endblock %}

{% block contents %}
{% include "snippets/navbar.html" %}
	<h1>Delete Artikel Confirmation</h1>
	<p>Apakah benar anda ingin menghapus artikel berikut:</p>
	<h3>{{artikel.judul}}</h3>
	<p>{{artikel.published}}</p>
	<form method='POST'>
		{% csrf_token %}
		<button type="submit" class="btn btn-outline-primary">Ya</button>
		<a class="btn btn-outline-danger" href="{% url 'blog:manage' %}">Tidak</a>
	</form>
{% endblock %}

blog/templates/blog/artikel_kategori_list.html
{% extends "base.html" %}

{% block head %}
	<title>Artikel</title>
{% endblock %}


{% block contents %}
{% include "snippets/navbar.html" %}


<div class="row">
	<div class="col-md-8">
		<h2 class="border-bottom">Kategori: {{kategori}}</h2><br>
		{% if is_paginated %}

			<nav aria-label="artikelPage">
			  <ul class="pagination">
			    
			    {% if page_obj.has_previous %}
			    	<li class="page-item">
				      <a class="page-link" href="{% url 'blog:category' kategori page_obj.previous_page_number%}">Previous</a>
				    </li>
				{% else %}
					<li class="page-item disabled">
				      <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
				    </li>
			    {% endif %}
			    
			    {% for page in paginator.page_range %}
			    	{% if page is page_obj.number %}
			    	<li class="page-item active" aria-current="page">
			    		<span class="page-link" href="#">{{page}}<span class="sr-only">(current)</span></span>
			    	</li>
			    	{% else %}
			    	<li class="page-item">
			    		<a class="page-link" href="{% url 'blog:category' kategori page %}">{{page}}</a>
			    	</li>
			    	{% endif %}
			    {% endfor %}
			    
			    {% if page_obj.has_next %}
			    	<li class="page-item">
				      <a class="page-link" href="{% url 'blog:category' kategori page_obj.next_page_number%}">Next</a>
				    </li>
				{% else %}
					<li class="page-item disabled">
				      <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
				    </li>
			    {% endif %}

			  </ul>
			</nav>

			{% endif %}

			{% for artikel in artikel_list %}
				<h3><a class="text-dark" href="{% url 'blog:detail' artikel.slug %}">{{artikel.judul}}</a></h3>
				<p>{{artikel.published}}</p>
				<p class="border-bottom">{{artikel.isi|truncatewords:50}} <a href="{% url 'blog:detail' artikel.slug %}">Selengkapnya</a></p>
			{% endfor %}
	</div>
	<div class="col-sm">
		<h3>Kategori lainnya</h3>
		<ul class="list-group list-group-flush">
			<li class="list-group-item"><a href="{% url 'blog:list' 1 %}"><b>Semua kategori</b></a></li>
		  	{% for kategori in kategori_list %}
		  		<li class="list-group-item"><a href="{% url 'blog:category' kategori 1%}">{{kategori}}</a></li>
		  	{% endfor %}
		</ul>
	</div>

</div>


{% endblock %}

blog/templates/blog/artikel_list.html
{% extends "base.html" %}

{% block head %}
	<title>Artikel</title>
{% endblock %}


{% block contents %}
{% include "snippets/navbar.html" %}


<div class="row">
	<div class="col-md-8">
		{% if is_paginated %}

			<nav aria-label="artikelPage">
			  <ul class="pagination">
			    
			    {% if page_obj.has_previous %}
			    	<li class="page-item">
				      <a class="page-link" href="{% url 'blog:list' page_obj.previous_page_number%}">Previous</a>
				    </li>
				{% else %}
					<li class="page-item disabled">
				      <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
				    </li>
			    {% endif %}
			    
			    {% for page in paginator.page_range %}
			    	{% if page is page_obj.number %}
			    	<li class="page-item active" aria-current="page">
			    		<span class="page-link" href="#">{{page}}<span class="sr-only">(current)</span></span>
			    	</li>
			    	{% else %}
			    	<li class="page-item">
			    		<a class="page-link" href="{% url 'blog:list' page %}">{{page}}</a>
			    	</li>
			    	{% endif %}
			    {% endfor %}
			    
			    {% if page_obj.has_next %}
			    	<li class="page-item">
				      <a class="page-link" href="{% url 'blog:list' page_obj.next_page_number%}">Next</a>
				    </li>
				{% else %}
					<li class="page-item disabled">
				      <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
				    </li>
			    {% endif %}

			  </ul>
			</nav>

			{% endif %}

			{% for artikel in artikel_list %}
				<h3><a class="text-dark" href="{% url 'blog:detail' artikel.slug %}">{{artikel.judul}}</a></h3>
				<p>Kategori: {{artikel.kategori}} | {{artikel.published}}</p>
				<p class="border-bottom">{{artikel.isi|truncatewords:50}} <a href="{% url 'blog:detail' artikel.slug %}">Selengkapnya</a></p>
			{% endfor %}
	</div>
	<div class="col-sm">
		<h3>Kategori</h3>
		<ul class="list-group list-group-flush">
		  	{% for kategori in kategori_list %}
		  		<li class="list-group-item"><a href="{% url 'blog:category' kategori 1 %}">{{kategori}}</a></li>
		  	{% endfor %}
		</ul>
	</div>

</div>


{% endblock %}

blog/templates/blog/artikel_manage.html
{% extends "base.html" %}

{% block head %}
<title>Manage</title>
{% endblock head %}

{% block contents %}
	<h3>Manage Artikel</h3>
{% include "snippets/navbar.html" %}

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Judul</th>
      <th scope="col">Kategori</th>
      <th scope="col">Published</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
   	{% for  artikel in artikel_list %} 
	    <tr>
	      <th scope="row">{{forloop.counter}}</th>
	      <td>{{artikel.judul}}</td>
	      <td>{{artikel.kategori}}</td>
	      <td>{{artikel.published}}</td>
	      <td>
	      <a class="btn btn-danger" href="{% url 'blog:update' artikel.id %}">Edit</a>
				<a class="btn btn-warning" href="{% url 'blog:delete' artikel.id %}">Delete</a>
	      </td>
	    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

blog/templates/blog/artikel_update.html
{% extends "base.html" %}

{% block head %}
<title>Update</title>
{% endblock %}

{% block contents %}
{% include "snippets/navbar.html" %}
	<h3>Update Artikel</h3>
	<form method="POST">
		{% csrf_token %}
		<div class="form-group">
		    <label for="{{form.judul.id_for_label}}">{{form.judul.label}}:</label>
		    <input type="text" class="form-control" name="{{form.judul.name}}" maxlength="{{form.judul.max}}" required id="{{form.judul.id_for_label}}" value="{{form.judul.value}}">    
		</div>

		<div class="form-group">
			<label for="{{form.isi.id_for_label}}">{{form.isi.label}}:</label>
			<textarea class="form-control" name="{{form.isi.name}}" rows="10" required id="{{form.isi.id_for_label}}">{{form.isi.value}}</textarea>
		</div>

		<div class="form-group">
		    <label for="{{form.kategori.id_for_label}}">{{form.kategori.label}}:</label>
		    <input type="text" class="form-control" name="{{form.kategori.name}}" maxlength="{{form.kategori.max}}" required id="{{form.kategori.id_for_label}}" value="{{form.kategori.value}}">    
		</div>

		<button type="submit" class="btn btn-warning">Update</button>
		<a class="btn btn-danger" href="{% url 'blog:manage' %}">Tidak</a>
	</form>
{% endblock %}

blog/templates/blog/create.html
{% extends "base.html" %}

{% block head %}
<title>Create</title>
{% endblock %}

{% block contents %}
{% include "snippets/navbar.html" %}
	<h3>Tambah Artikel</h3>
	<form method="POST">
		{% csrf_token %}
		<div class="form-group">
		    <label for="{{form.judul.id_for_label}}">{{form.judul.label}}:</label>
		    <input type="text" class="form-control" name="{{form.judul.name}}" maxlength="{{form.judul.max}}" required id="{{form.judul.id_for_label}}">    
		</div>

		<div class="form-group">
			<label for="{{form.isi.id_for_label}}">{{form.isi.label}}:</label>
			<textarea class="form-control" name="{{form.isi.name}}" rows="10" required id="{{form.isi.id_for_label}}"></textarea>
		</div>

		<div class="form-group">
		    <label for="{{form.kategori.id_for_label}}">{{form.kategori.label}}:</label>
		    <input type="text" class="form-control" name="{{form.kategori.name}}" maxlength="{{form.kategori.max}}" required id="{{form.kategori.id_for_label}}">    
		</div>

		<button type="submit" class="btn btn-primary">Tambah</button>
	</form>
{% endblock %}

blog/templates/blog/detail.html
{% extends "base.html" %}

{% block head %}
	<title>{{artikel.judul}}</title>
{% endblock %}

{% block contents %}
{% include "snippets/navbar.html" %}

<div class="row">
	<div class="col-md-8">
		<h1>{{artikel.judul}}</h1>
		<h5>Kategori: {{artikel.kategori}} | {{artikel.published}}</h5>
		<p>{{artikel.isi}}</p>	
	</div>
	<div class="col-sm">
		<h3>Kategori</h3>
		<ul class="list-group list-group-flush">
		  	{% for kategori in kategori_list %}
		  		<li class="list-group-item"><a href="{% url 'blog:category' kategori 1%}">{{kategori}}</a></li>
		  	{% endfor %}
		</ul>
		<h3>Artikel Serupa</h3>

		<ul class="list-group list-group-flush">
		  	{% for artikel in artikel_serupa %}
		  		
		  		{% if forloop.counter is not 3 %}
		  		<li class="list-group-item">
		  			<h5><a href="{% url 'blog:detail' artikel.slug %}">{{artikel.judul}}</a></h5>
		  			<p>{{artikel.published|date}}</p>
		  		</li>
		  		{% endif %}

		  	{% endfor %}
		  	<li class="list-group-item"><a href="{% url 'blog:category' artikel.kategori 1%}">Selengkapnya</a></li>
		</ul>

	</div>
</div>
	
{% endblock %}