account/urls.py
from django.conf.urls import url,include
from . import views

urlpatterns = [
	url(r'^login',views.LoginView.as_view(),name='login'),
	url(r'^logout',views.LogoutIndex.as_view(),name='logout'),
	url(r'^profile',views.View_Profile,name='view_profile'),
    url(r'^signup',views.signup, name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^password_reset_index/',views.PasswordResetIndex.as_view(),name='password_reset_view'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_ \ -]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.PasswordConfirmResetIndex.as_view(),name='password_reset_confirm'),
    url(r'^password_reset_complete_view/',views.PasswordCompleteResetIndex.as_view(),name='password_reset_complete_view'),
    url(r'^password_reset_done_view/',views.PasswordResetDoneIndex.as_view(),name='password_reset_done_view'),
    url(r'^upload',views.UploadIndex.as_view(),name='upload'),
]

blog/urls.py
from django.conf.urls import url,include
from .views import (
	CreateView,
	ArtikelDetailView,
	ArtikelManageView,
	ArtikelUpdateView,
	ArtikelDeleteView,
	ArtikelListView,
	ArtikelKategoriListView,
	)

urlpatterns = [
    url(r'^create', CreateView.as_view(),name='create'),
    url(r'^detail/(?P<slug>[\w-]+)$',ArtikelDetailView.as_view(),name='detail'),
	url(r'^manage/$',ArtikelManageView.as_view(),name='manage'),
	url(r'^manage/update/(?P<pk>\d+)$',ArtikelUpdateView.as_view(),name='update'),
	url(r'^manage/delete/(?P<pk>\d+)$',ArtikelDeleteView.as_view(),name='delete'),
	url(r'^(?P<page>\d+)$',ArtikelListView.as_view(),name='list'),
	url(r'^kategori/(?P<kategori>[\w]+)/(?P<page>\d+)$',ArtikelKategoriListView.as_view(),name='category'),

]

my_website/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import index 
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',index.as_view(),name='index'),
    ###
    url(r'^artikel/',include('blog.urls',namespace='blog')),
    url(r'^account/',include('account.urls',namespace='account')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/snippets/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      {% if user.is_authenticated %}
            
          

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Position
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'blog:create' %}">author</a>
              <a class="dropdown-item" href="{% url 'blog:manage' %}">Editor</a>
            </div>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'account:view_profile' %}">Profile</a>
           </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
            </li>
          </li>
      {% else %}

            <li class="nav-item">
            <a class="nav-link" href="{% url 'account:login' %}">Login</a>
             </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'account:signup' %}">Signup</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'account:password_reset_view' %}">Forgot Password</a>
            </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div class="margin-bottom:40px">
</nav>

templates/snippets/scripts.html
{% load static %}
<script src="{% static 'vendor/jquery/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'vendor/popper/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

templates/snippets/style.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">	