blog/urls.py
from django.conf.urls import url,include
from .views import (
	CreateView,
	ArtikelDetailView,
	ArtikelManageView,
	ArtikelUpdateView,
	ArtikelDeleteView,
	ArtikelListView,
	ArtikelKategoriListView,
	)

urlpatterns = [
    url(r'^create', CreateView.as_view(),name='create'),
    url(r'^detail/(?P<slug>[\w-]+)$',ArtikelDetailView.as_view(),name='detail'),
	url(r'^manage/$',ArtikelManageView.as_view(),name='manage'),
	url(r'^manage/update/(?P<pk>\d+)$',ArtikelUpdateView.as_view(),name='update'),
	url(r'^manage/delete/(?P<pk>\d+)$',ArtikelDeleteView.as_view(),name='delete'),
	url(r'^(?P<page>\d+)$',ArtikelListView.as_view(),name='list'),
	url(r'^kategori/(?P<kategori>[\w]+)/(?P<page>\d+)$',ArtikelKategoriListView.as_view(),name='category'),

]

my_website/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import index 
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',index.as_view(),name='index'),
    ###
    url(r'^artikel/',include('blog.urls',namespace='blog')),
    url(r'^account/',include('account.urls',namespace='account')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	{% block head %}
	<title></title>
	{% endblock %}
			{% include "snippets/style.html" %}
</head>

<body>
{% block contents %}

{% endblock %}
	{% include "snippets/scripts.html" %}
</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block head %}
<title>Home</title>
{% endblock %}

{% block contents %}
{% include "snippets/navbar.html" %}

  <div class="row">
    {% for artikel in latest_artikel_list %}
    <div class="col-sm-4">
        	<div class="card">
            <div class="card-body">
              <h5 class="card-title" ><a href="{% url 'blog:category' artikel.kategori 1 %}">{{artikel.kategori}}</a></h5>
              <h6 class="card-subtitle mb-2 text-dark">{{artikel.judul}}</h6>
              <h6 class="card-subtitle mb-2 text-muted">{{artikel.published|date}}</h6>
              <p class="card-text">{{artikel.isi|truncatewords:10}}</p>
              <a href="{% url 'blog:detail' artikel.slug %}" class="card-link">Selengkapnya</a>
            </div>
          </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}